### ISSUE TITLE
Webpack 4 Entrypoint undefined

### ISSUE THREAD

**Issue by ErikSchierboom** [jantimon/html-webpack-plugin#895]
## Description

When working with Webpack 4, people can now start with zero-configuration. This allows one to quickly get started with using Webpack, without any of the configuration hassle. Trying out Webpack 4, I tried to create a minimal configuration that uses the `HtmlWebpackPlugin` (see the Config section). While functionally working, I do get a warning about an undefined entrypoint. 

While I can ignore this warning, I'm not sure if there actually is a problem or if there is something I can do about it. If there is something wrong in my configuration, it would be great if a message was printed that explains how to fix it.

I can reproduce this is in both `development` and `production` mode.

### Error Message & Stack Trace

```
Entrypoint undefined = index.html
```

### Config

Minimal version:

```js
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
    plugins: [new HtmlWebpackPlugin()]
};
```

More explicit version that also has the warning:

```js
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
  entry: './src/index.js',
  output: {
    path: __dirname + '/dist',
    filename: 'bundle.js'
  },

  plugins: [new HtmlWebpackPlugin()]
};
```

Version with HTML loader that also has the warning:

```js
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
  entry: './src/index.js',
  output: {
    path: __dirname + '/dist',
    filename: 'bundle.js'
  },
  module: {
    rules: [
      { test: /\.html$/i, loader: 'html-loader' },
    ]
  },

  plugins: [new HtmlWebpackPlugin()]
};
```

## Environment

```
node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
Node.js v8.9.3
win32 10.0.14393

npm --version
5.6.0

npm ls webpack
webpack@4.1.1

npm ls html-webpack-plugin
html-webpack-plugin@3.0.6
```

**Comment by sukonzer** [comment]
![233](https://user-images.githubusercontent.com/2359717/37201843-ca1dfc68-23c3-11e8-80a0-ef90dc361cb9.png)
```
html-webpack-plugin 3.0.6
```
I have an same issue with you

**Comment by jantimon** [comment]
The entry point is injected into webpack - what would be the correct way to give it a name?

**Comment by ErikSchierboom** [comment]
Is this a Webpack issue then?

**Comment by jantimon** [comment]
Does it produce any error or is this just a cosmetic issue?

**Comment by ErikSchierboom** [comment]
It is just a cosmetic issue, so it is not really that important. It just might be confusing for new users.

**Comment by jantimon** [comment]
If someone can find out how we can change it I would love to merge it into the plugin

**Comment by ErikSchierboom** [comment]
@sokra Do you perhaps know how the `HtmlWebpackPlugin` can ensure that Webpack does not specify the entrypoint as `undefined`? (see the discussion in this issue)

**Comment by yash2code** [comment]
its giving same error even when providing template and filename options .

**Comment by aurelienlewin** [comment]
Same issue.

```
plugins: [
        new HtmlWebpackPlugin({
            template: './src/index.html',
            …
```

```
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
       [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html 15.2 KiB {0} [built]
```

**Comment by fralonra** [comment]
Same issue

### webpack.config.js
```javascript
...
plugins: [
      ...
      new HtmlWebPackPlugin({
        title: '...',
        template: path.resolve(folderSrc, 'index.html'),
        filename: 'index.html',
        hash: true
      })
    ]
...
```

### Output
```bash
...
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
...
```

### Env
```
node v9.7.1
npm 5.7.1
webpack 4.1.1
html-webpack-plugin 3.0.6
```

**Comment by zD98** [comment]
```
    stats: {
        ...
        children: false, 
        ...
    },
```

Setting the property `children` to false will show off the log info.
But I don't know how to change it or solve it.

**Comment by ecanro** [comment]
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html

the same error is not cosmetic, since the script stops and the bundle does not end

**Comment by sokra** [comment]
> Do you perhaps know how the HtmlWebpackPlugin can ensure that Webpack does not specify the entrypoint as undefined? (see the discussion in this issue)

yep, provide all arguments to the SingleEntryPlugin constructor:

https://github.com/jantimon/html-webpack-plugin/blob/8131d8bb1dc9b185b3c1709264a3baf32ef799bc/lib/compiler.js#L50

The last one is the entrypoint name.

**Comment by kn7007** [comment]
I'm just install and config html-loader. Then it working properly. So you can try

**Comment by jantimon** [comment]
Fixed in 3.0.7

**Comment by jantimon** [comment]
Please report bugs here #900

**Comment by ErikSchierboom** [comment]
Thanks for the fix @jantimon!

**Comment by jantimon** [comment]
@ErikSchierboom please note that we will probably revert this change because of #900

**Comment by atilkan** [comment]
The last version did not fix hmr for me. Html files doesn't update after compile.

**Comment by avaleriani** [comment]
HMR not working for me in 3.1.0 and still entrypoint appears as undefined.

**Comment by jantimon** [comment]
Can you please try older versions and let me know which version works with HMR for you?

**Comment by glowkeeper** [comment]
Same issue

**Comment by zenoven** [comment]
same issue in v3.1.0 with webpack config below

```js
...
const config = {
  mode: mode,
  entry: {
    index: './index.js'
  },
  context: projectPath,
  output: {
    filename: '[name].[chunkhash:22].js',
    chunkFilename: '[name].[chunkhash:22].js',
    path: buildPath
  },

  plugins: [
    new HTMLWebpackPlugin({
      template: 'index.html',
    })
  ]
}
```

**Comment by superjose** [comment]
There should have been some regression issues between 3.0.7 and 3.1.0, installing 3.0.7 again solves the issue:

```
"dependencies": {
    "html-webpack-plugin": "3.0.7",
  }
```

**Comment by superjose** [comment]
There seems to be a regression from 3.0.7 to 3.1.0. Installing 3.0.7 fixes the issue:
```
"devDependencies": {
    "html-webpack-plugin": "3.0.7",
}
```

**Comment by jpike88** [comment]
Was also getting this error in addition to the entrypoint undefined one

![screen shot 2018-04-05 at 10 54 07 am](https://user-images.githubusercontent.com/9585787/38346503-b18aaec4-38bf-11e8-8f3c-a8bb8e140419.png)

Downgrading to 3.0.7 fixed the issue for me too.

**Comment by jantimon** [comment]
**We introduced a fix in 3.0.7 but removed it again in 3.0.8** because of many errors which were reported in #900 

@jpike88 this is unrelated to the current issue could you please create a new issue?

**Comment by jpike88** [comment]
sorry, moved onto fuse-box...

**Comment by superjose** [comment]
@jantimon Bam! Guess that explains it. Thanks for the update. There should be something in the documentation that states the current problem, and the workaround. People will be spending several hours trying to fix a problem that it's not their own.

**Comment by jantimon** [comment]
@superjose - actually it’s not an error just a meaningless log message :)
So the workaround would be to ignore it (although I really don’t like that approach)
I would be very happy for any help or idea how we or the webpack-dev-server team could fix #900 so we can apply the solution of 3.0.7 again

**Comment by jnosornov** [comment]
Any updates on the current issue...

Having the same issue

**Comment by ecanro** [comment]
In the past it was a job for extract-text-webpack-plugin.

Unfortunately said plugin does not play well with webpack 4.

According to Michael Ciniawsky:

extract-text-webpack-plugin reached a point where maintaining it become too much of a burden and it’s not the first time upgrading a major webpack version was complicated and cumbersome due to issues with it

mini-css-extract-plugin is here to overcome those issues

**Comment by leedorian** [comment]
Same issue here, v3.2.0

**Comment by rodgerpaulo** [comment]
same issue here :(
`v3.2.0`

**Comment by kl2karpenko** [comment]
Same here!) Please do something!)

**Comment by danitrimujianto** [comment]
same issue.. need help....

**Comment by yuanzx** [comment]
Same issue here, v3.2.0

**Comment by jantimon** [comment]
Please see https://github.com/jantimon/html-webpack-plugin/issues/895#issuecomment-379006202

**Comment by erosenberg** [comment]
Same issue here, v3.2.0

**Comment by ShaneCallanan** [comment]
Hope someone can fix #900 soon so this issue can be swiftly resolved.
I can't get through the build phase atm because of it.

**Comment by superjose** [comment]
@jantimon Thanks for the response! I think everyone will come flocking around without actually reading the issue. Why not put it on the front of the README.md that it's a false positive?

**Comment by AhHa45** [comment]
it's not a meaningless log issue as the build fails...

**Comment by jantimon** [comment]
@AhHa45 It does not cause the build to fail - it might be the last log message of webpack **before** your build fails.  

If it really causes a build failure please open a bug report with a reproduction example.

All others Please see #895 (comment)
